# Generated by Django 4.1.3 on 2022-11-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=254, upload_to='file-uploads/%Y/%m/%D/'),
        ),
    ]
