# Generated by Django 4.1.3 on 2022-11-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_alter_staff_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.TextField(default=True, max_length=70),
        ),
    ]
