# Generated by Django 4.1.3 on 2022-11-25 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_staff_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
