# Generated by Django 4.1.3 on 2022-11-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_staff_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='email',
            new_name='admin_email',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='admin',
            new_name='admin_name',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='phone',
            new_name='admin_phone',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='date_established',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='logo',
        ),
        migrations.AddField(
            model_name='hospital',
            name='date_due',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='date_from',
            field=models.DateField(null=True),
        ),
    ]
