# Generated by Django 4.1.3 on 2022-11-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_alter_hospital_admin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='region',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
