# Generated by Django 4.1.3 on 2022-11-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0027_alter_staff_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='created_by',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
